INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (100, 'Comic Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (101, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (102, 'Books');

INSERT INTO SUPPLIER (ID, NAME) VALUES (100, 'Mercado livre');
INSERT INTO SUPPLIER (ID, NAME) VALUES (101, 'Amazon');

INSERT INTO PRODUCT(ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (100, 'Iphone 17 Pro', 100, 101, 20, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (101, 'Velocidade Furiosa', 101, 100, 5, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES( 102, 'Pai rico e pai pobre', 100, 101, 3, CURRENT_TIMESTAMP);